language: java

addons:
  sonarcloud:
    organization: "hugogamaliel"
    token:
      secure: "X28S9PgqeOSMr+PaMz64eLTqjCSDLk75xMd8T/hOjJDHuZKQxev9bwPCj/DHg/hx3jWaHvQcuWxAB+pLYEcxzQZcSp/b+7ieyVCPRxbwIPQm0TsJYH38uDk1kAU7AemvUSTTKA+uHYHUlEVFoCimJBjcmp9XVo2eBDW7uxmEfitAGa2AZuP4fazT7SEJji0pih23zXtJIvUli3vGbbHd0EJ3nrIAUVVM2fwGShw/tXH6lmUHpPbmGbnsroFc6GRIva+BfSq5lhn5BtcB3D7KWYZkJyuJFnFTvaBL/X2XKWr6CuDfwsNHTE0T872FuBNryC5Nd9cy4HCRdGRuslQ7C3+gJGsJNmS02EOuIu93A59uuZxxFaf5AOrjH5dEwgrkvO1tO8335J6jgp8kFA2h3BS933QbmUK5eC7NPwQoiC1M04AoxDZyr/HTcJULX4Hc1VRSSCxjep8wORMASuCbMpcft/YDdTLHVTPFBSLDzhPasrreBNTXCi5yzygKa2tzFUTOv+HUDWjUOssnGDv0cybGOyct9Gwtmj9oF3a51+BsaTuTK2pwAu7XLuVbkeSb32z1aLWRcBqb65yuaQBrTVCqTPuP0dq7w2z0tDzkVFw/8MzwSdCNXry67aRJBEbwCswjJ1uxZ7DDr+piW2IyrAFn0tKiE11ui/2xe2Llars=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=hugogamaliel_ci-spring